starter: Доработан стартовый скрипт

diff --git a/starter.sh.in b/starter.sh.in
--- a/starter.sh.in
+++ b/starter.sh.in
@@ -2,20 +2,38 @@
 
 set -x
 
-for i in {1..10}; do
-  echo "Waiting X11 server starting..."
-  if [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ]; then
-    break
-  fi
-  sleep 1
-done
+# 1. Получаем ID активной сессии текущего пользователя
+# (Игнорируем SSH-сессии, если проверяем именно локальную графику)
+SESSION_ID=$(loginctl list-sessions --no-legend | grep -w "$USER" | awk '{print $1}' | head -n 1)
 
-if [ -z "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
-  echo "ERROR: No X11 server found!" >&2
+if [ -z "$SESSION_ID" ]; then
+  echo "The graphical session was not found (the user is not logged in)"
   exit 1
 fi
 
-echo "DISPLAY: $DISPLAY"
-echo "WAYLAND_DISPLAY: $WAYLAND_DISPLAY"
+# 2. Проверяем тип сессии (x11 или wayland)
+SESSION_TYPE=$(loginctl show-session "$SESSION_ID" -p Type --value)
+
+# 3. Проверяем, активна ли сессия прямо сейчас (не находится ли в фоне/спящем режиме)
+SESSION_STATE=$(loginctl show-session "$SESSION_ID" -p State --value)
+
+if [[ "$SESSION_TYPE" =~ ^(x11|wayland)$ ]] && [ "$SESSION_STATE" = "active" ]; then
+  echo "The graphical session ($SESSION_TYPE) is active and displayed on the screen."
+else
+  echo "The graphical session is not active (type: $SESSION_TYPE)"
+  exit 1
+fi
+
+# Похоже, что графическая сессия активна. Дожидаемся появления переменных DISPLAY/WAYLAND_display
+echo "Checking DISPLAY or WAYLAND_DISPLAY variables is initialized"
+if [ -z "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
+  echo "Variables is missing, try to obtain the value of the DISPLAY variable from the session data"
+  SESSION_DISPLAY="$(loginctl show-session "$SESSION_ID" -p Display --value)"
+  if [ -z "$SESSION_DISPLAY" ]; then
+    echo "Error retrieving the value of the DISPLAY variable, exit!" >&2
+    exit 1
+  fi
+  export DISPLAY="$SESSION_DISPLAY"
+fi
 
 @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@/@PROJECT_NAME@ "$@"
