starter: Расширено логгирование shell-стартера

diff --git a/starter.sh.in b/starter.sh.in
--- a/starter.sh.in
+++ b/starter.sh.in
@@ -2,11 +2,13 @@
 
 # Цикл ожидания графического сервера (максимум 15 секунд)
 for i in {1..15}; do
-  # Проверяем, доступны ли переменные для X11 или Wayland
+  echo "Waiting for X11/Wayland server starting..."
   if [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ]; then
+    echo "Waiting for X11/Wayland server starting... OK"
     break
   fi
-  # Попытка подтянуть переменные из активного сессионного окружения dbus/systemd
+  echo "Waiting for X11/Wayland server starting... MISSING"
+  echo "Let's try get envs from active session environment and repeat checking..."
   if command -v systemctl &>/dev/null; then
     eval $(systemctl --user show-environment | grep -E '^(DISPLAY|WAYLAND_DISPLAY|XAUTHORITY)=')
   fi
@@ -15,8 +17,12 @@ done
 
 # Если графика так и не появилась, завершаем работу с ошибкой (systemd попробует еще раз через RestartSec)
 if [ -z "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
-  echo "Ошибка: Графический сервер (X11/Wayland) не обнаружен." >&2
+  echo "ERROR: No X11/Wayland server found!" >&2
   exit 1
 fi
+
+echo "Environment: DISPLAY=$DISPLAY"
+echo "Environment: WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
+echo "Environment: XAUTHORITY=$XAUTHORITY"
 
 @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@/@PROJECT_NAME@ "$@"
